/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sysvent.forms;

import com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException;
import static com.sysvent.forms.Consultar_Empleados.jTextUser6;
import static com.sysvent.forms.Consultar_Empleados.mostrarTabla;
import com.uabcs.db.DBConnection;
import com.uabcs.model.empleado;
import com.uabcs.model.producto;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Consultar_Productos extends javax.swing.JInternalFrame {
    

    /**
     * Creates new form Consultar_Productos
     */
    public Consultar_Productos(){
        
        initComponents();
        inhabilitarTexto();
        try {
            mostrarTabla("");
        } catch (ClassNotFoundException | SQLException | InstantiationException ex) {
            Logger.getLogger(Consultar_Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        botonActualizar.setVisible(false);
        botonCancelar.setVisible(false);
        botonGuardar.setVisible(false);
    }
           private static DBConnection  conn = new DBConnection();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   public static String idProducto;
   private static String atributo;
            public static void mostrarTabla(String valorAtributo)throws ClassNotFoundException, SQLException, InstantiationException{
         atributo = comboBuscar.getSelectedItem().toString();
        DefaultTableModel modeloEmpleado = new DefaultTableModel();
        modeloEmpleado.addColumn("CODIGO BARRA");
        modeloEmpleado.addColumn("NOMBRE");
        modeloEmpleado.addColumn("FAMILIA");
        modeloEmpleado.addColumn("DEPTO");
        modeloEmpleado.addColumn("PRECIO COMPRA");
        modeloEmpleado.addColumn("PRECIO VENTA");
        modeloEmpleado.addColumn("STOCK");
        modeloEmpleado.addColumn("TIPO DE VENTA");
        tablaProducto.setModel(modeloEmpleado);
        String sql = "";
        if(valorAtributo.equals("")){
            sql="SELECT * FROM producto";
        }else{
            if(atributo.equals("FamiliaProducto")){
                sql="SELECT * FROM producto INNER JOIN familiaProducto ON  "
                    + "producto.id_famproFK = familiaProducto.id_fampro WHERE nombre_fampro LIKE '%"+valorAtributo+"%'";
             } 
                else if(atributo.equals("Departamento")){
                    sql="SELECT * FROM producto INNER JOIN departamento ON  "
                      + "producto.id_depFK = departamento.id_dep WHERE nombre_dep LIKE '%"+valorAtributo+"%'";
                }
                else{
                    sql="SELECT * FROM producto WHERE "+atributo+" LIKE '%"+valorAtributo+"%'";
                }   
        }
       
        
        String datoProducto[]=new String[9];    
        Connection con = conn.Conectar();
        Statement st;
        st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);
  
        while(rs.next()){
            idProducto=rs.getString(1);
            datoProducto[0]=rs.getString(2);
            datoProducto[1]=rs.getString(3);
            datoProducto[2]=rs.getString(4);
            datoProducto[3]=rs.getString(5);
            datoProducto[4]=rs.getString(6);
            datoProducto[5]=rs.getString(7);
            datoProducto[6]=rs.getString(8);
            datoProducto[7]=rs.getString(9);
            datoProducto[2] = producto.familiaInner(Integer.parseInt(datoProducto[2]));
            datoProducto[3] = producto.departamentoInner(Integer.parseInt(datoProducto[3]));
            modeloEmpleado.addRow(datoProducto);
        }   
        
        
        tablaProducto.setModel(modeloEmpleado);
    }

    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buscarProducto = new javax.swing.JTextField();
        botonRestablecer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProducto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jComboBox2Dep = new javax.swing.JComboBox<>();
        jComboBox1Marca = new javax.swing.JComboBox<>();
        jTextCod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextPrecioCompra = new javax.swing.JTextField();
        jTextPrecioVenta = new javax.swing.JTextField();
        jTextStock = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonNuevo = new javax.swing.JButton();
        jComboBox1Tipo = new javax.swing.JComboBox<>();
        botonActualizar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        botonMostrar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        comboBuscar = new javax.swing.JComboBox<>();

        setBorder(null);
        setClosable(true);
        setResizable(true);
        setMaximumSize(new java.awt.Dimension(1186, 521));
        setMinimumSize(new java.awt.Dimension(1186, 521));
        setPreferredSize(new java.awt.Dimension(1186, 521));

        jPanel1.setBackground(new java.awt.Color(242, 149, 27));
        jPanel1.setMaximumSize(new java.awt.Dimension(1184, 521));
        jPanel1.setMinimumSize(new java.awt.Dimension(1184, 521));
        jPanel1.setPreferredSize(new java.awt.Dimension(1184, 521));

        buscarProducto.setMaximumSize(new java.awt.Dimension(200, 25));
        buscarProducto.setMinimumSize(new java.awt.Dimension(200, 25));
        buscarProducto.setPreferredSize(new java.awt.Dimension(200, 25));
        buscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarProductoActionPerformed(evt);
            }
        });
        buscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buscarProductoKeyPressed(evt);
            }
        });

        botonRestablecer.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botonRestablecer.setText("Restablecer");
        botonRestablecer.setPreferredSize(new java.awt.Dimension(80, 30));
        botonRestablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRestablecerActionPerformed(evt);
            }
        });

        jScrollPane1.setAutoscrolls(true);

        tablaProducto.setAutoCreateRowSorter(true);
        tablaProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaProducto.setAutoscrolls(false);
        tablaProducto.setMaximumSize(new java.awt.Dimension(550, 317));
        tablaProducto.setMinimumSize(new java.awt.Dimension(550, 317));
        tablaProducto.setPreferredSize(new java.awt.Dimension(550, 317));
        tablaProducto.setRowMargin(0);
        jScrollPane1.setViewportView(tablaProducto);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Producto:");

        jPanel2.setBackground(new java.awt.Color(184, 178, 178));

        jComboBox2Dep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Departamento--", "Abarrotes", "Frutas y Verduras", "Otro", "" }));
        jComboBox2Dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2DepActionPerformed(evt);
            }
        });

        jComboBox1Marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Selecciona Marca--", "Coca-Cola", "Pepsi", "Bimbo", "Sabritas", "Barcel", "Lala" }));
        jComboBox1Marca.setAutoscrolls(true);
        jComboBox1Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1MarcaActionPerformed(evt);
            }
        });

        jTextCod.setMaximumSize(new java.awt.Dimension(200, 25));
        jTextCod.setMinimumSize(new java.awt.Dimension(200, 25));
        jTextCod.setPreferredSize(new java.awt.Dimension(200, 25));
        jTextCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCodActionPerformed(evt);
            }
        });
        jTextCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCodKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Codigo");

        jTextNombre.setMaximumSize(new java.awt.Dimension(200, 25));
        jTextNombre.setMinimumSize(new java.awt.Dimension(200, 25));
        jTextNombre.setPreferredSize(new java.awt.Dimension(200, 25));
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });
        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });

        jTextPrecioCompra.setMaximumSize(new java.awt.Dimension(200, 25));
        jTextPrecioCompra.setMinimumSize(new java.awt.Dimension(200, 25));
        jTextPrecioCompra.setPreferredSize(new java.awt.Dimension(200, 25));
        jTextPrecioCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPrecioCompraActionPerformed(evt);
            }
        });
        jTextPrecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPrecioCompraKeyTyped(evt);
            }
        });

        jTextPrecioVenta.setMaximumSize(new java.awt.Dimension(200, 25));
        jTextPrecioVenta.setMinimumSize(new java.awt.Dimension(200, 25));
        jTextPrecioVenta.setPreferredSize(new java.awt.Dimension(200, 25));
        jTextPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPrecioVentaActionPerformed(evt);
            }
        });
        jTextPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextPrecioVentaKeyTyped(evt);
            }
        });

        jTextStock.setMaximumSize(new java.awt.Dimension(200, 25));
        jTextStock.setMinimumSize(new java.awt.Dimension(200, 25));
        jTextStock.setName(""); // NOI18N
        jTextStock.setPreferredSize(new java.awt.Dimension(200, 25));
        jTextStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextStockKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Nombre del Producto");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Precio de Compra");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Precio de Venta");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Cantidad");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Tipo de venta");

        botonGuardar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonNuevo.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botonNuevo.setText("Nuevo");
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        jComboBox1Tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione Tipo de Venta--", "Granel", "Kg", "Pza", "Paquete" }));

        botonActualizar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botonActualizar.setText("Actualizar");
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox1Tipo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTextPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox2Dep, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1Marca, 0, 182, Short.MAX_VALUE))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBox1Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2Dep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextPrecioCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox1Tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(botonCancelar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonGuardar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonNuevo)
                            .addComponent(botonActualizar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        botonMostrar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botonMostrar.setText("Mostrar");
        botonMostrar.setPreferredSize(new java.awt.Dimension(80, 30));
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });

        botonModificar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botonModificar.setText("Modificar");
        botonModificar.setPreferredSize(new java.awt.Dimension(80, 30));
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        botonEliminar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.setPreferredSize(new java.awt.Dimension(80, 30));
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        comboBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Buscar Por--", "CodigoBarra", "Nombre_Pro", "FamiliaProducto", "Departamento", "Tipo_Venta" }));
        comboBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 56, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(botonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(comboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRestablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1186, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1186, 521));
    }// </editor-fold>//GEN-END:initComponents

    private void buscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarProductoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buscarProductoActionPerformed

    private void jComboBox2DepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2DepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2DepActionPerformed

    private void jComboBox1MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1MarcaActionPerformed

    private void jTextCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCodActionPerformed
        // TODO add your handling code here:
        jTextCod.transferFocus();
    }//GEN-LAST:event_jTextCodActionPerformed

    private void jTextCodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCodKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextCodKeyTyped

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
        jTextNombre.transferFocus();
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jTextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextNombreKeyTyped

    private void jTextPrecioCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPrecioCompraActionPerformed
        // TODO add your handling code here:}
        jTextPrecioCompra.transferFocus();
    }//GEN-LAST:event_jTextPrecioCompraActionPerformed

    private void jTextPrecioCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPrecioCompraKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextPrecioCompraKeyTyped

    private void jTextPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPrecioVentaActionPerformed
        // TODO add your handling code here:
        jTextPrecioVenta.transferFocus();
    }//GEN-LAST:event_jTextPrecioVentaActionPerformed

    private void jTextPrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextPrecioVentaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextPrecioVentaKeyTyped

    private void jTextStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextStockKeyTyped
        // TODO add your handling code here:}
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextStockKeyTyped

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed

        // TODO add your handling code here:
        int UNIQUE_CONSTRAINT_VIOLATED =1062;
        String codigo = jTextCod.getText();
        String nombre = jTextNombre.getText();
        Double precioCompra;
        Double precioVenta;
        int stock;
        try{
            precioCompra = Double.valueOf(jTextPrecioCompra.getText());
            precioVenta = Double.valueOf(jTextPrecioVenta.getText());
            stock  = Integer.parseInt(jTextStock.getText());

        } catch(NumberFormatException ex){
             jTextNombre.requestFocus();
             return;
        }
        String tipoVenta= jComboBox1Tipo.getSelectedItem().toString();
        int fampro = jComboBox1Marca.getSelectedIndex();
        int dep = jComboBox2Dep.getSelectedIndex();

        if (codigo.length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un Codigo");
            jTextNombre.requestFocus();
            return;
        }
        if (nombre.length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un Nombre");
            jTextNombre.requestFocus();
            return;
        }
        if (precioCompra == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un Precio de Compra");
            jTextNombre.requestFocus();
            return;
        }
        if (precioVenta == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un Precio de Venta");
            jTextNombre.requestFocus();
            return;
        }
        if (stock == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un No. de Stock");
            jTextNombre.requestFocus();
            return;
        }
        if (fampro == 0) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar la Familia del Producto");
            jTextNombre.requestFocus();
            return;
        }
        if (dep == 0) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar el Departamento del Producto");
            jTextNombre.requestFocus();
            return;
        }
        if (jComboBox1Tipo.getSelectedIndex()== 0) {
            JOptionPane.showMessageDialog(null, "Debes seleccionar el Tipo de Venta del Producto");
            jTextNombre.requestFocus();
            return;
        }

        try {
            producto.createProducto(codigo, nombre, fampro, dep, precioCompra, precioVenta, stock, tipoVenta); 
            borrarTexto();
            inhabilitarTexto();
            mostrarTabla("");
            botonGuardar.setVisible(false);
            botonCancelar.setVisible(false);
            botonNuevo.setVisible(true);
        }  catch (MySQLIntegrityConstraintViolationException e) {
            String msg = "Advertencia";
            if (UNIQUE_CONSTRAINT_VIOLATED == e.getErrorCode ()) {
                // manejar la excepcion de la manera que corresponda segun la logica de negocio, posiblemente agregando un mensaje de error; tambien se
                // podria levantar la excepcion a una capa superior mediante "throw e";
                msg = "No se puede duplicar el codigo del producto";
                borrarTexto();
            }
            JOptionPane.showMessageDialog(null,msg,null,JOptionPane.WARNING_MESSAGE);
        } catch (ClassNotFoundException | SQLException | InstantiationException ex) {
            Logger.getLogger(Agregar_Producto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        // TODO add your handling code here:
        jTextCod.setEnabled(true);
        habilitarTexto();
        botonGuardar.setVisible(true);
        botonCancelar.setVisible(true);
        botonNuevo.setVisible(false);
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        // TODO add your handling code here:
        String nombre = jTextNombre.getText();
        Double precioCompra= Double.valueOf(jTextPrecioCompra.getText());
        Double precioVenta=Double.valueOf(jTextPrecioVenta.getText());
        int stock = Integer.parseInt(jTextStock.getText());
         int id = Integer.parseInt(idBuscar);
        try {
            producto.updateProducto(id, nombre, precioCompra, precioVenta, stock);
            mostrarTabla("");
            borrarTexto();
            inhabilitarTexto();
            botonActualizar.setVisible(false);
            botonCancelar.setVisible(false);
            botonGuardar.setVisible(false);
            botonNuevo.setVisible(true);
            
        } catch (ClassNotFoundException | SQLException | InstantiationException ex) {
            Logger.getLogger(Consultar_Productos.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        
                
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        botonCancelar.setVisible(false);
        botonActualizar.setVisible(false);
        botonGuardar.setVisible(false);
        botonNuevo.setVisible(true);
        inhabilitarTexto();
        borrarTexto();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void comboBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBuscarActionPerformed

    private void buscarProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarProductoKeyPressed
        try {
            // TODO add your handling code here:
            mostrarTabla(buscarProducto.getText());
        } catch (ClassNotFoundException | SQLException | InstantiationException ex) {
            Logger.getLogger(Consultar_Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarProductoKeyPressed

    private void botonRestablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRestablecerActionPerformed
        // TODO add your handling code here:}
        buscarProducto.setText("");
    }//GEN-LAST:event_botonRestablecerActionPerformed

    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
        try {
            // TODO add your handling code here:
            mostrarTabla("");
        } catch (ClassNotFoundException | SQLException | InstantiationException ex) {
            Logger.getLogger(Consultar_Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonMostrarActionPerformed
private static String idBuscar;
    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        // TODO add your handling code here:
        String nombre = jTextNombre.getText();
       int filaSeleccionada = tablaProducto.getSelectedRow();
       if(filaSeleccionada>=0){
           botonNuevo.setVisible(false);
           botonGuardar.setVisible(false);
           botonActualizar.setVisible(true);
           botonCancelar.setVisible(true);
           jTextCod.setEnabled(false);
           habilitarTexto();
           jComboBox2Dep.setEnabled(false);
           jComboBox1Tipo.setEnabled(false);
           jComboBox1Marca.setEnabled(false);
            idBuscar=idProducto;
            jTextNombre.setText(tablaProducto.getValueAt(filaSeleccionada,1).toString());
            jTextPrecioCompra.setText(tablaProducto.getValueAt(filaSeleccionada,4).toString());
            jTextPrecioVenta.setText(tablaProducto.getValueAt(filaSeleccionada,5).toString());
            jTextStock.setText(tablaProducto.getValueAt(filaSeleccionada,6).toString());
           
       } else{
            JOptionPane.showMessageDialog(null, "No haz seleccionado ningun elemento");

       }
        
        
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
             int idBuscarEliminar;
        int filaSeleccionadaEmpleado = tablaProducto.getSelectedRow();
        if(filaSeleccionadaEmpleado>=0){
               idBuscarEliminar=Integer.parseInt(idProducto);

            if (JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar Empleado?", "WARNING",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    producto.deleteProducto(idBuscarEliminar);
                    mostrarTabla("");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                } else {
                    
                try {
                    mostrarTabla("");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
            
            
        } else{
            JOptionPane.showMessageDialog(null, "No haz seleccionado ningun elemento");
        }
          
                                           

    }//GEN-LAST:event_botonEliminarActionPerformed
private void borrarTexto(){
        jTextCod.setText("");
        jTextNombre.setText("");
        jTextPrecioCompra.setText("");
        jTextPrecioVenta.setText("");
        jTextStock.setText("");
        jComboBox1Tipo.setSelectedIndex(0);
        jComboBox1Marca.setSelectedIndex(0);
        jComboBox2Dep.setSelectedIndex(0);
    }
    private void inhabilitarTexto(){
        jComboBox1Marca.setEnabled(false);
        jComboBox1Tipo.setEnabled(false);
        jComboBox2Dep.setEnabled(false);
        jTextCod.setEditable(false);
        jTextNombre.setEditable(false);
        jTextPrecioCompra.setEditable(false);
        jTextPrecioVenta.setEditable(false);
        jTextStock.setEditable(false);
    }
     private void habilitarTexto(){
        jComboBox1Marca.setEnabled(true);
        jComboBox1Tipo.setEnabled(true);
        jComboBox2Dep.setEnabled(true);
        jTextCod.setEditable(true);
        jTextNombre.setEditable(true);
        jTextPrecioCompra.setEditable(true);
        jTextPrecioVenta.setEditable(true);
        jTextStock.setEditable(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonRestablecer;
    private static javax.swing.JTextField buscarProducto;
    private static javax.swing.JComboBox<String> comboBuscar;
    private javax.swing.JComboBox<String> jComboBox1Marca;
    private javax.swing.JComboBox<String> jComboBox1Tipo;
    private javax.swing.JComboBox<String> jComboBox2Dep;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextCod;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextPrecioCompra;
    private javax.swing.JTextField jTextPrecioVenta;
    private javax.swing.JTextField jTextStock;
    private static javax.swing.JTable tablaProducto;
    // End of variables declaration//GEN-END:variables
}
