/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sysvent.forms;

import com.uabcs.db.DBConnection;
import com.uabcs.model.proveedor;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Consultar_Proveedores extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consultar_Proveedores
     */
    public Consultar_Proveedores() {
        initComponents();
        inhabilitarTexto();
        botonGuardar.setVisible(false);
        botonCancelar.setVisible(false);
        botonActualizar.setVisible(false);
        botonNuevo.setVisible(true);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProveedor = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jTextBuscar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        botonMostrar = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        comboBusarProv = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        jTextNombre = new javax.swing.JTextField();
        jTextDireccion = new javax.swing.JTextField();
        jTextTel = new javax.swing.JTextField();
        jTextApePA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextApeMa = new javax.swing.JTextField();
        comboFam = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        botonNuevo = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();

        setBorder(null);
        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(242, 149, 27));

        tablaProveedor.setAutoCreateRowSorter(true);
        tablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaProveedor.setMaximumSize(new java.awt.Dimension(550, 317));
        tablaProveedor.setMinimumSize(new java.awt.Dimension(550, 317));
        tablaProveedor.setPreferredSize(new java.awt.Dimension(550, 317));
        jScrollPane1.setViewportView(tablaProveedor);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Proveedor");

        jTextBuscar.setMaximumSize(new java.awt.Dimension(200, 25));
        jTextBuscar.setMinimumSize(new java.awt.Dimension(200, 25));
        jTextBuscar.setPreferredSize(new java.awt.Dimension(200, 25));
        jTextBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBuscarActionPerformed(evt);
            }
        });
        jTextBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextBuscarKeyPressed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton1.setText("Restablecer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botonMostrar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botonMostrar.setText("Mostrar");
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });

        botonModificar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botonModificar.setText("Modificar");
        botonModificar.setPreferredSize(new java.awt.Dimension(93, 25));
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });

        botonEliminar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        botonEliminar.setText("Eliminar");
        botonEliminar.setPreferredSize(new java.awt.Dimension(93, 25));
        botonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarActionPerformed(evt);
            }
        });

        comboBusarProv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Buscar Por--", "Nombre", "Apellido_Paterno", "Apellido_Materno", "Empresa_Asoc", "Telefono", "Direccion", " " }));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setMaximumSize(new java.awt.Dimension(523, 347));
        jPanel2.setMinimumSize(new java.awt.Dimension(523, 347));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Nombre(s)");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Direccion");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Telefono");

        botonGuardar.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        jTextNombre.setMaximumSize(new java.awt.Dimension(175, 25));
        jTextNombre.setMinimumSize(new java.awt.Dimension(175, 25));
        jTextNombre.setPreferredSize(new java.awt.Dimension(175, 25));
        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });

        jTextDireccion.setMaximumSize(new java.awt.Dimension(175, 60));
        jTextDireccion.setMinimumSize(new java.awt.Dimension(175, 60));
        jTextDireccion.setPreferredSize(new java.awt.Dimension(175, 60));

        jTextTel.setMaximumSize(new java.awt.Dimension(175, 25));
        jTextTel.setMinimumSize(new java.awt.Dimension(175, 25));
        jTextTel.setPreferredSize(new java.awt.Dimension(175, 25));
        jTextTel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextTelKeyTyped(evt);
            }
        });

        jTextApePA.setMaximumSize(new java.awt.Dimension(175, 25));
        jTextApePA.setMinimumSize(new java.awt.Dimension(175, 25));
        jTextApePA.setPreferredSize(new java.awt.Dimension(175, 25));
        jTextApePA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextApePAKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Apellido Paterno");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Apellido Materno");

        jTextApeMa.setMaximumSize(new java.awt.Dimension(175, 25));
        jTextApeMa.setMinimumSize(new java.awt.Dimension(175, 25));
        jTextApeMa.setPreferredSize(new java.awt.Dimension(175, 25));
        jTextApeMa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextApeMaKeyTyped(evt);
            }
        });

        comboFam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccione una--", "Coca-Cola", "Pepsi", "Bimbo", "Sabritas", "Barcel", "Lala", "Otros(s)" }));
        comboFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboFamActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Familia");

        botonNuevo.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        botonNuevo.setText("Nuevo");
        botonNuevo.setPreferredSize(new java.awt.Dimension(77, 23));
        botonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoActionPerformed(evt);
            }
        });

        botonActualizar.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        botonActualizar.setText("Actualizar");
        botonActualizar.setPreferredSize(new java.awt.Dimension(77, 23));
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });

        botonCancelar.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        botonCancelar.setText("Cancelar");
        botonCancelar.setPreferredSize(new java.awt.Dimension(77, 23));
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextApePA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(94, 94, 94)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboFam, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addComponent(jTextApeMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(botonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(comboFam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextApePA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextApeMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1062, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(botonMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboBusarProv, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMostrar)
                    .addComponent(botonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(botonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBusarProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1186, 521));
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
        int empresafk;
        String nombre = jTextNombre.getText();
        String apellido_paterno = jTextApePA.getText();
        String apellido_materno = jTextApeMa.getText();
        String telefono = jTextTel.getText();
        String direccion = jTextDireccion.getText();

        empresafk = comboFam.getSelectedIndex();

        if (nombre.length() == 0) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un Nombre");
            jTextNombre.requestFocus();
            return;
        }
        if (apellido_paterno.length() == 0 && apellido_materno.length() == 0) {
            JOptionPane.showMessageDialog(null, "Debe ingresar almenos un apellido");
            jTextApePA.requestFocus();
            return;
        }
        if (telefono.length()==0 && direccion.length()==0) {
            JOptionPane.showMessageDialog(null, "Debe ingresar almenos una referencia");
            jTextTel.requestFocus();
            return;
        }
        if(empresafk==0) {
            JOptionPane.showMessageDialog(null, "Debe seleccionar la Familia");
            comboBusarProv.requestFocus();
            return;
        }

        try {
            proveedor.createProveedor(nombre, apellido_paterno, apellido_materno, empresafk, telefono, direccion);
            botonGuardar.setVisible(false);
            botonCancelar.setVisible(false);
            botonNuevo.setVisible(true);
            limpiarTexto();
            inhabilitarTexto();
            mostrarTabla("");
        } catch (SQLException | ClassNotFoundException | InstantiationException ex) {
            Logger.getLogger(Agregar_Proveedores.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_botonGuardarActionPerformed

    private void jTextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
            // JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_jTextNombreKeyTyped

    private void jTextTelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextTelKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextTelKeyTyped

    private void jTextApePAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextApePAKeyTyped
        // TODO add your handling code here:}
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
            // JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_jTextApePAKeyTyped

    private void jTextApeMaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextApeMaKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
            // JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }
    }//GEN-LAST:event_jTextApeMaKeyTyped

    private void comboFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboFamActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        limpiarTexto();
        inhabilitarTexto();
        botonNuevo.setVisible(true);
        botonGuardar.setVisible(false);
        botonCancelar.setVisible(false);
    }//GEN-LAST:event_botonCancelarActionPerformed
    public void limpiarTexto(){
        jTextApeMa.setText("");
        jTextApePA.setText("");
        jTextDireccion.setText("");
        jTextTel.setText("");
        jTextNombre.setText("");
    }
    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        // TODO add your handling code here:
        habilitarTexto();
        botonNuevo.setVisible(false);
        botonGuardar.setVisible(true);
        botonCancelar.setVisible(true);
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        // TODO add your handling code here:
        String nombre = jTextNombre.getText();
        String apellidoP = jTextApePA.getText();
        String apellidoM = jTextApeMa.getText();
        String phone = jTextTel.getText();
        String direccion = jTextDireccion.getText();
        int id = Integer.parseInt(idBuscar);
        try {
            proveedor.updateProv(id, nombre, apellidoP, apellidoM, phone, direccion);
            limpiarTexto();
            inhabilitarTexto();
            botonGuardar.setVisible(false);
            botonNuevo.setVisible(true);
            botonActualizar.setVisible(false);
            botonCancelar.setVisible(false); 
            mostrarTabla("");
        } catch (ClassNotFoundException | SQLException | InstantiationException ex) {
            Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
        try {
            // TODO add your handling code here:
            mostrarTabla("");
        } catch (ClassNotFoundException | SQLException | InstantiationException ex) {
            Logger.getLogger(Consultar_Proveedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botonMostrarActionPerformed

    private void inhabilitarTexto(){
        jTextNombre.setEditable(false);
        jTextApePA.setEditable(false);
        jTextApeMa.setEditable(false);
        jTextDireccion.setEditable(false);
        jTextTel.setEditable(false);
        comboFam.setEnabled(false);
    }
     private void habilitarTexto(){
        jTextNombre.setEditable(true);
        jTextApePA.setEditable(true);
        jTextApeMa.setEditable(true);
        jTextDireccion.setEditable(true);
        jTextTel.setEditable(true);
        comboFam.setEnabled(true);
    }
    
    
    private void botonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarActionPerformed
        // TODO add your handling code here:
          int idBuscarEliminar;
        int filaSeleccionada = tablaProveedor.getSelectedRow();
        if(filaSeleccionada>=0){
               idBuscarEliminar=Integer.parseInt(idProv);

            if (JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar Proveedor?", "WARNING",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    proveedor.deleteProv(idBuscarEliminar);
                    mostrarTabla("");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                } else {
                    
                try {
                    mostrarTabla("");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
            
            
        } else{
            JOptionPane.showMessageDialog(null, "No haz seleccionado ningun elemento");
        }
    }//GEN-LAST:event_botonEliminarActionPerformed
       
    private static String idBuscar;

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        // TODO add your handling code here:

       int filaSeleccionada = tablaProveedor.getSelectedRow();
       if(filaSeleccionada>=0){
            botonGuardar.setVisible(false);
            botonNuevo.setVisible(false);
            botonActualizar.setVisible(true);
            botonCancelar.setVisible(true);
            habilitarTexto();
            comboFam.setEnabled(false);
            idBuscar=idProv;
            jTextNombre.setText(tablaProveedor.getValueAt(filaSeleccionada,0).toString());
            jTextApePA.setText(tablaProveedor.getValueAt(filaSeleccionada,1).toString());
            jTextApeMa.setText(tablaProveedor.getValueAt(filaSeleccionada,2).toString());
            jTextTel.setText(tablaProveedor.getValueAt(filaSeleccionada,4).toString());
            jTextDireccion.setText(tablaProveedor.getValueAt(filaSeleccionada,5).toString());           
       } else{
            JOptionPane.showMessageDialog(null, "No haz seleccionado ningun elemento");
       }
    }//GEN-LAST:event_botonModificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jTextBuscar.setText("");
        jTextBuscar.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBuscarKeyPressed
        // TODO add your handling code here:
        String valor = jTextBuscar.getText();
        try {
           mostrarTabla(valor);
        } catch (ClassNotFoundException | SQLException | InstantiationException ex) {
            Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }   
    }//GEN-LAST:event_jTextBuscarKeyPressed

    private void jTextBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBuscarActionPerformed
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JButton botonNuevo;
    private static javax.swing.JComboBox<String> comboBusarProv;
    private javax.swing.JComboBox<String> comboFam;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextApeMa;
    private javax.swing.JTextField jTextApePA;
    private javax.swing.JTextField jTextBuscar;
    private javax.swing.JTextField jTextDireccion;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextTel;
    private static javax.swing.JTable tablaProveedor;
    // End of variables declaration//GEN-END:variables
private static String atributo;
public static String idProv;
           private static DBConnection  conn = new DBConnection();

public static void mostrarTabla(String valorAtributo)throws ClassNotFoundException, SQLException, InstantiationException{
         atributo = comboBusarProv.getSelectedItem().toString();
        DefaultTableModel modeloProveedor = new DefaultTableModel();
        modeloProveedor.addColumn("NOMBRE");
        modeloProveedor.addColumn("APELLIDO_PATERNO");
        modeloProveedor.addColumn("APELLIDO_MATERNO");
        modeloProveedor.addColumn("EMPRESA");
        modeloProveedor.addColumn("TELEFONO");
        modeloProveedor.addColumn("DIRECCION");
        tablaProveedor.setModel(modeloProveedor);
        String sql = "";
        if(valorAtributo.equals("")){
            sql="SELECT * FROM proveedor";
        }else if(atributo.equals("Empresa_Asoc")){
            sql="SELECT * FROM proveedor INNER JOIN familiaProducto ON  "
            + "proveedor.empresa_asoc = familiaProducto.id_fampro WHERE nombre_fampro LIKE '%"+valorAtributo+"%'";
        }else{
            sql="SELECT * FROM proveedor WHERE "+atributo+" LIKE '%"+valorAtributo+"%'";
        }
        String datoProveedor[]=new String[7];    
        Connection con = conn.Conectar();
        Statement st;
        st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);
  
        while(rs.next()){
            idProv=rs.getString(1);
            datoProveedor[0]=rs.getString(2);
            datoProveedor[1]=rs.getString(3);
            datoProveedor[2]=rs.getString(4);
            datoProveedor[3]=rs.getString(5);
            datoProveedor[4]=rs.getString(6);
            datoProveedor[5]=rs.getString(7);
            datoProveedor[3]=proveedor.familia(Integer.parseInt(datoProveedor[3]));
            modeloProveedor.addRow(datoProveedor);
        }   
        tablaProveedor.setModel(modeloProveedor);

    }



}


