/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sysvent.forms;


import com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException;
import com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException;
import com.uabcs.db.DBConnection;
import com.uabcs.model.empleado;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Consultar_Empleados extends javax.swing.JInternalFrame {

    /**
     * Creates new form Consultar_Empleados
     */
    public Consultar_Empleados() {
        initComponents();
        inhabilitarText();
       }
       private static String atributo;
           private static DBConnection  conn = new DBConnection();
           public static String idEmpleado;
      
        public static void mostrarTabla(String valorAtributo)throws ClassNotFoundException, SQLException, InstantiationException{
         atributo = ComboBuscar.getSelectedItem().toString();
        DefaultTableModel modeloEmpleado = new DefaultTableModel();
        modeloEmpleado.addColumn("NOMBRE");
        modeloEmpleado.addColumn("APELLIDO_PATERNO");
        modeloEmpleado.addColumn("APELLIDO_MATERNO");
        modeloEmpleado.addColumn("DIRECCION");
        modeloEmpleado.addColumn("TELEFONO");
        modeloEmpleado.addColumn("USERNAME");
        modeloEmpleado.addColumn("PASSWORD");
        modeloEmpleado.addColumn("TIPO USUARIO");
        tablaEmpleado.setModel(modeloEmpleado);
        String sql = "";
        if(valorAtributo.equals("")){
            sql="SELECT * FROM empleado";
        }else{
            sql="SELECT * FROM empleado WHERE "+atributo+" LIKE '%"+valorAtributo+"%'";
        }
        String datoEmpleado[]=new String[8];    
        Connection con = conn.Conectar();
        Statement st;
        st = con.createStatement();
        ResultSet rs = st.executeQuery(sql);
  
        while(rs.next()){
            idEmpleado=rs.getString(1);
            datoEmpleado[0]=rs.getString(2);
            datoEmpleado[1]=rs.getString(3);
            datoEmpleado[2]=rs.getString(4);
            datoEmpleado[3]=rs.getString(5);
            datoEmpleado[4]=rs.getString(6);
            datoEmpleado[5]=rs.getString(7);
            datoEmpleado[6]=rs.getString(8);
            datoEmpleado[7]=rs.getString(9);
            modeloEmpleado.addRow(datoEmpleado);
        }   
        tablaEmpleado.setModel(modeloEmpleado);

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEmpleado = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextApePa = new javax.swing.JTextField();
        jTextApeMa = new javax.swing.JTextField();
        jTextCel = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextUser6 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextBuscar = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        ComboBuscar = new javax.swing.JComboBox<>();

        setBorder(null);
        setClosable(true);
        setMaximumSize(new java.awt.Dimension(1186, 521));
        setMinimumSize(new java.awt.Dimension(1186, 521));
        setPreferredSize(new java.awt.Dimension(1186, 521));

        jPanel1.setBackground(new java.awt.Color(242, 149, 27));

        tablaEmpleado.setAutoCreateRowSorter(true);
        tablaEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        tablaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tablaEmpleado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tablaEmpleado.setMaximumSize(new java.awt.Dimension(550, 317));
        tablaEmpleado.setMinimumSize(new java.awt.Dimension(550, 317));
        tablaEmpleado.setPreferredSize(new java.awt.Dimension(550, 317));
        jScrollPane1.setViewportView(tablaEmpleado);

        jPanel2.setBackground(new java.awt.Color(184, 178, 178));
        jPanel2.setMaximumSize(new java.awt.Dimension(523, 347));
        jPanel2.setMinimumSize(new java.awt.Dimension(523, 347));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Apellido Paterno");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Apellido Materno");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Direccion");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("Telefono");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Usuario");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Contraseña");

        jTextNombre.setMaximumSize(new java.awt.Dimension(200, 25));
        jTextNombre.setMinimumSize(new java.awt.Dimension(200, 25));
        jTextNombre.setPreferredSize(new java.awt.Dimension(200, 25));
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });
        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombreKeyTyped(evt);
            }
        });

        jTextApePa.setMaximumSize(new java.awt.Dimension(200, 25));
        jTextApePa.setMinimumSize(new java.awt.Dimension(200, 25));
        jTextApePa.setPreferredSize(new java.awt.Dimension(200, 25));
        jTextApePa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextApePaActionPerformed(evt);
            }
        });
        jTextApePa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextApePaKeyTyped(evt);
            }
        });

        jTextApeMa.setMaximumSize(new java.awt.Dimension(200, 25));
        jTextApeMa.setMinimumSize(new java.awt.Dimension(200, 25));
        jTextApeMa.setPreferredSize(new java.awt.Dimension(200, 25));
        jTextApeMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextApeMaActionPerformed(evt);
            }
        });
        jTextApeMa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextApeMaKeyTyped(evt);
            }
        });

        jTextCel.setMaximumSize(new java.awt.Dimension(200, 25));
        jTextCel.setMinimumSize(new java.awt.Dimension(200, 25));
        jTextCel.setPreferredSize(new java.awt.Dimension(200, 25));
        jTextCel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCelActionPerformed(evt);
            }
        });
        jTextCel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextCelKeyTyped(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton4.setText("Guardar");
        jButton4.setVisible(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.setVisible(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextUser6.setMaximumSize(new java.awt.Dimension(120, 25));
        jTextUser6.setMinimumSize(new java.awt.Dimension(120, 25));
        jTextUser6.setPreferredSize(new java.awt.Dimension(120, 25));
        jTextUser6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUser6ActionPerformed(evt);
            }
        });

        jPasswordField1.setMaximumSize(new java.awt.Dimension(120, 25));
        jPasswordField1.setMinimumSize(new java.awt.Dimension(120, 25));
        jPasswordField1.setPreferredSize(new java.awt.Dimension(120, 25));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton5.setText("Actualizar");
        jButton5.setEnabled(false);
        jButton5.setRolloverEnabled(false);
        jButton5.setVisible(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton9.setText("Nuevo");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "General" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setText("Tipo Usuario");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setToolTipText("");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(4, 4, 4))
                            .addComponent(jLabel5)))
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jTextCel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextApeMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextApePa, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(105, 105, 105)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextUser6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextUser6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton9)
                            .addComponent(jButton5)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextApePa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextApeMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton8.setText("Mostrar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Buscar usuario:");

        jTextBuscar.setMaximumSize(new java.awt.Dimension(120, 25));
        jTextBuscar.setMinimumSize(new java.awt.Dimension(120, 25));
        jTextBuscar.setPreferredSize(new java.awt.Dimension(120, 25));
        jTextBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBuscarActionPerformed(evt);
            }
        });
        jTextBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextBuscarKeyPressed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jButton7.setText("Restablecer");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        ComboBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Buscar Por--", "Nombre", "Apellido_Paterno", "Apellido_Materno", "Direccion", "Telefono", "Usuario_Login" }));
        ComboBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton7)))
                        .addContainerGap(202, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton6)
                    .addComponent(jButton8)
                    .addComponent(jLabel9)
                    .addComponent(jTextBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1186, 521));
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
        jPasswordField1.transferFocus();
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int UNIQUE_CONSTRAINT_VIOLATED=1062;
        String nombre = jTextNombre.getText();
        String apellidoP = jTextApePa.getText();
        String apellidoM = jTextApeMa.getText();
        String direccion = jTextArea1.getText();
        String phone = jTextCel.getText();
        String usuario = jTextUser6.getText();
        String password = String.valueOf(jPasswordField1.getPassword());
        String tipoUsuario = jComboBox1.getSelectedItem().toString();
        
          if (nombre.length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar un Nombre");
            jTextNombre.requestFocus();
            return;
        }

        if (apellidoP.length() == 0 && apellidoM.length()==0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar al menos un Apellido");
            jTextApePa.requestFocus();
            return;
        }


        if (usuario.length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar nombre de Usuario");
            jTextUser6.requestFocus();
            return;
        }

        if (password.length() == 0) {
            JOptionPane.showMessageDialog(null, "Debes ingresar una Contraseña");
            jTextUser6.requestFocus();
            return;
        }
        
        try {
            empleado.createEmpleado(nombre, apellidoP, apellidoM, direccion, phone, usuario, password,tipoUsuario);
            mostrarTabla("");
             limpiarTexto();
             inhabilitarText();
             jButton4.setVisible(false);
             jButton2.setVisible(false);
             jButton9.setVisible(true);

        }catch (MySQLIntegrityConstraintViolationException e) {
                String msg = "Advertencia";
                if (UNIQUE_CONSTRAINT_VIOLATED == e.getErrorCode ()) {
                    // manejar la excepcion de la manera que corresponda segun la logica de negocio, posiblemente agregando un mensaje de error; tambien se
                    // podria levantar la excepcion a una capa superior mediante "throw e";
                    msg = "El nombre de usuario ya se encuentra en uso, intenta con otro";
                }
                JOptionPane.showMessageDialog(null,msg,null,JOptionPane.WARNING_MESSAGE);
       }catch (SQLException | InstantiationException | ClassNotFoundException ex) {
            Logger.getLogger(Agregar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void limpiarTexto(){
        jTextApeMa.setText("");
        jTextApePa.setText("");
        jTextCel.setText("");
        jTextArea1.setText("");
        jTextNombre.setText("");
        jTextUser6.setText("");
        jPasswordField1.setText("");
          jButton3.setVisible(true);
             jButton6.setVisible(true);
             
        
    }
    
    private void inhabilitarText(){
     jPasswordField1.setEditable(false);
     jTextApeMa.setEditable(false);
     jTextApePa.setEditable(false);
     jTextCel.setEditable(false);
     jTextArea1.setEditable(false);
     jTextNombre.setEditable(false);
     jTextUser6.setEditable(false);
     jButton2.setVisible(false);
     jButton4.setVisible(false);
     jComboBox1.setEditable(false);
    }
     private void habilitarText(){
     jPasswordField1.setEditable(true);
     jTextApeMa.setEditable(true);
     jTextApePa.setEditable(true);
     jTextCel.setEditable(true);
     jTextArea1.setEditable(true);
     jTextNombre.setEditable(true);
     jTextUser6.setEditable(true);
     jComboBox1.setEditable(true);

    }
    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      limpiarTexto();
      inhabilitarText();
      jButton4.setVisible(false);
      jButton9.setVisible(true);
      jButton5.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed
       private String idBuscar; 

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int filaSeleccionadaEmpleado = tablaEmpleado.getSelectedRow();
        if(filaSeleccionadaEmpleado>=0){
            jButton5.setEnabled(true);
            jButton5.setVisible(true);
            jButton4.setVisible(false);
            jButton9.setVisible(false);
            jButton2.setVisible(true);
            jComboBox1.setEnabled(false);
            habilitarText();
            idBuscar=idEmpleado;
            jTextNombre.setText(tablaEmpleado.getValueAt(filaSeleccionadaEmpleado,0).toString());
            jTextApePa.setText(tablaEmpleado.getValueAt(filaSeleccionadaEmpleado,1).toString());
            jTextApeMa.setText(tablaEmpleado.getValueAt(filaSeleccionadaEmpleado,2).toString());
            jTextArea1.setText(tablaEmpleado.getValueAt(filaSeleccionadaEmpleado,3).toString());
            jTextCel.setText(tablaEmpleado.getValueAt(filaSeleccionadaEmpleado,4).toString());
            jTextUser6.setEnabled(false);
            jPasswordField1.setEnabled(false);
        } else{
            JOptionPane.showMessageDialog(null, "No haz seleccionado ningun elemento");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String nombre = jTextNombre.getText();
        String apellidoP = jTextApePa.getText();
        String apellidoM = jTextApeMa.getText();
        String direccion = jTextArea1.getText();
        String phone = jTextCel.getText();
        int id = Integer.parseInt(idBuscar);
        try {
            empleado.updateEmpleado(id,nombre, apellidoP, apellidoM, direccion, phone);
            limpiarTexto();
            jButton2.setVisible(false);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
            jButton9.setVisible(true);
            inhabilitarText();
            mostrarTabla("");
        } catch (ClassNotFoundException | SQLException | InstantiationException ex) {
            Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int idBuscarEliminar;
        int filaSeleccionadaEmpleado = tablaEmpleado.getSelectedRow();
        if(filaSeleccionadaEmpleado>=0){
               idBuscarEliminar=Integer.parseInt(idEmpleado);

            if (JOptionPane.showConfirmDialog(null, "¿Estas seguro de eliminar Empleado?", "WARNING",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                try {
                    empleado.deleteEmpleado(idBuscarEliminar);
                    mostrarTabla("");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                } else {
                    
                try {
                    mostrarTabla("");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
                }
                }
            
            
        } else{
            JOptionPane.showMessageDialog(null, "No haz seleccionado ningun elemento");
        }
          
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextUser6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUser6ActionPerformed
        // TODO add your handling code here:
        jTextUser6.transferFocus();
    }//GEN-LAST:event_jTextUser6ActionPerformed

    private void jTextBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBuscarActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_jTextBuscarActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jTextBuscar.setText("");
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            // TODO add your handling code here:
              mostrarTabla("");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void ComboBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBuscarActionPerformed
       
    }//GEN-LAST:event_ComboBuscarActionPerformed

    private void jTextBuscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextBuscarKeyPressed
           // TODO add your handling code here:
         String valor = jTextBuscar.getText();
        try {
           mostrarTabla(valor);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(Consultar_Empleados.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_jTextBuscarKeyPressed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        habilitarText();
        jTextUser6.setEnabled(true);
        jPasswordField1.setEnabled(true);
        jComboBox1.setEnabled(true);
        jButton9.setVisible(false);
        jButton4.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(false);
        jButton6.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jTextNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
            // JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreKeyTyped

    private void jTextApePaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextApePaKeyTyped
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
            // JOptionPane.showMessageDialog(null, "Ingrese solo letras");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTextApePaKeyTyped

    private void jTextApeMaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextApeMaKeyTyped
            // TODO add your handling code here:
             char c = evt.getKeyChar();
                if (Character.isDigit(c)) {
                    getToolkit().beep();
                    evt.consume();
                    // JOptionPane.showMessageDialog(null, "Ingrese solo letras");
                }
    }//GEN-LAST:event_jTextApeMaKeyTyped

    private void jTextCelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCelKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextCelKeyTyped

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
        jTextNombre.transferFocus();
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jTextApePaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextApePaActionPerformed
        // TODO add your handling code here:
        jTextApePa.transferFocus();
    }//GEN-LAST:event_jTextApePaActionPerformed

    private void jTextApeMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextApeMaActionPerformed
        // TODO add your handling code here:
        jTextApeMa.transferFocus();
    }//GEN-LAST:event_jTextApeMaActionPerformed

    private void jTextCelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCelActionPerformed
        // TODO add your handling code here
        jTextCel.transferFocus();
    }//GEN-LAST:event_jTextCelActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        jComboBox1.transferFocus();
    }//GEN-LAST:event_jComboBox1ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JComboBox<String> ComboBuscar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextApeMa;
    private javax.swing.JTextField jTextApePa;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextBuscar;
    private javax.swing.JTextField jTextCel;
    private javax.swing.JTextField jTextNombre;
    public static javax.swing.JTextField jTextUser6;
    private static javax.swing.JTable tablaEmpleado;
    // End of variables declaration//GEN-END:variables
}
